apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: placenl
data:
  prometheus.yml: |-
    global:
      scrape_interval:     5s # kan hoger ofc
      evaluation_interval: 5s

    scrape_configs:
      - job_name: prometheus # metrics over prom zelf
        static_configs:
          - targets: ['localhost:9090']
      - job_name: chief
        static_configs:
          - targets: ['chief.placenl.nl']